name: "Deploy Container Test"

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          file: ./Dockerfile
          env:
            PUBLIC_AUTH_TOKEN=${{ secrets.SECRET_AUTH_TOKEN }}
          secrets: |
            secret_auth_token=${{ secrets.SECRET_AUTH_TOKEN }}